### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by konno-tech** [konno-tech/furima-31063#10]
# URL
https://furima-31063.herokuapp.com/
# Basic認証
- ID：admin
- PASS：2222 
# 出品者情報
- email：sample@sample.com
- PASS：1qaz1qaz
# 購入者情報
- email：sam2@sample.com
- PASS：1qaz1qaz
# 購入用カードの情報
- 番号：4242424242424242
- 期限：3/33
- コード：123

**Comment by snkw-works** [comment]
今野さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
**商品詳細機能**
- [x] 商品出品時に登録した「商品の説明」が表示できるよう実装しましょう
現在は詳細ページにて、どの商品も「商品説明」と表示されてしまう状態です。

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by konno-tech** [comment]
ご確認のほど、よろしくお願いいたします。

**Comment by snkw-works** [comment]
今野さん、再度ご提出いただきありがとうございます！
挙動確認させて頂きましたが、指摘点の修正が確認できました。
全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**

**Comment by konno-tech** [comment]
ありがとうございます！
